### PR TITLE
Fix mute of simulcasted video tracks with < 3 encodings

### LINKED ISSUE #112: Simulcast video tracks with lower resolution will always be pending
**Describe the bug**
When using simulcast with low resolutions, video tracks will always be in a pending state. This causes events like mute status changes to never be recognized by the server or broadcast to clients.

**Server**
- Version: [0.12.5]
- Environment: Docker image on fly.io

**Client**
- SDK: js
- Version: 0.12.1

**To Reproduce**
1. Start a conference with lower video resolution (`VideoPresets43.vga` and simulcast enabled. 
2. Have debug logging enabled
3. Mute/unmute the video track
4. Note that the `mute status changed` log is ever printed

**Expected behavior**
Tracks should not be considered pending if the total number of expected tracks are being sent, regardless of that number.

**Additional context**
This appears to be getting caused by a combination of how the JS Client SDK handles simulcast tracks with lower resolution and expectations of the livekit-server.

In `participant.go - SetTrackMuted`, if a track is considered pending the function returns early and does not change the Muted status server side or send `onTrackUpdated` events. https://github.com/livekit/livekit-server/blob/1bcaf9d0ea2681aadb6f60bfe42062f252903a42/pkg/rtc/participant.go#L586-L588

In `participant.go - onMediaTrack`, pending tracks are only removed from the pending status if the track isn't simulcasted, or if the number of established tracks is 3. https://github.com/livekit/livekit-server/blob/1bcaf9d0ea2681aadb6f60bfe42062f252903a42/pkg/rtc/participant.go#L824-L827

In the JS Client SDK, if the starting resolution is not high enough, only one simulcast track (for a total of two tracks) will be sent. https://github.com/livekit/client-sdk-js/blob/64dc4b52fc363fe34e8ac58427f233868b0d0e7e/src/room/participant/LocalParticipant.ts#L389-L417

Either the client code would need to be modified to always sent two tracks, or the sever code needs to remove the assumption that simulcasted tracks will always have three active encoding levels.

### PR DESCRIPTION
**Pull request by davidzhao**
resolves #112

### CODE REVIEW

**Comment by bekriebel** [comment]
This does fix the mute status issue. However, I think something is still not quite right when lower resolution is being sent. It seems like some encodings are still missed.

For example, with `resolution: VideoPresets43.hd`, in the server side logs I see (one audio track and three video tracks):
```json
{"level":"debug","ts":1631658123.9954596,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_ZWYn8dB9A9Mt","track":"d4088e69-ea43-4941-bbb0-20974096ef57","rid":""}
{"level":"debug","ts":1631658124.0963626,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_ZWYn8dB9A9Mt","track":"a989e063-2767-4005-9091-7c04c9b858d1","rid":"q"}
{"level":"debug","ts":1631658124.1184497,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_ZWYn8dB9A9Mt","track":"a989e063-2767-4005-9091-7c04c9b858d1","rid":"h"}
{"level":"debug","ts":1631658124.3078728,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_ZWYn8dB9A9Mt","track":"a989e063-2767-4005-9091-7c04c9b858d1","rid":"f"}
```
This matches what I see with `localParticipant.videoTracks.get("<track_id>").track.encodings`

However, with `VideoPresets43.qhd` I see this: (one audio and two video tracks):
```json
{"level":"debug","ts":1631658634.6161678,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_MJE5Ry8qRk8S","track":"d92dc535-1a21-4960-9461-b448f505b61b","rid":""}
{"level":"debug","ts":1631658635.019182,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_MJE5Ry8qRk8S","track":"0638f832-e54a-446d-94fc-2b6e09cba7eb","rid":"h"}
{"level":"debug","ts":1631658635.1954706,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_MJE5Ry8qRk8S","track":"0638f832-e54a-446d-94fc-2b6e09cba7eb","rid":"f"}
```
Even though on the client `track.encodings` shows three tracks with rid f, h, and q.

If I go down to `resolution: VideoPresets43.qvga` I see this: (one audio and one video track):
```json
{"level":"debug","ts":1631658775.37457,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_oVhXFap67HM5","track":"316cf84c-0614-4129-b928-22ef57e422c7","rid":""}
{"level":"debug","ts":1631658775.4780617,"logger":"livekit","caller":"rtc/participant.go:771","msg":"mediaTrack added","participant":"bekitTest01","pID":"PA_oVhXFap67HM5","track":"bd2dc023-7a28-4b74-a166-e55e5e17a039","rid":"f"}
```
and on the client side I see two encodings, f and h, as expected.

Oddly, though, if I go down to `VideoPresets43.vga`, I properly see two tracks on both client and server. I don't know why some encoding types seem to be getting missed at various resolution levels. This might also be a client side bug... I haven't tracked down where this one is coming from yet. It consistently does the same thing, though.

**Comment by davidzhao** [comment]
this is expected and caused by Browser's internal logic on max layers to send for a particular resolution.

For `VideoPresets43.qhd`, even though we request the browser to send three encodings, but it decides to only send two. We try to deal with it to the best of our abilities on the server side, but do not end up updating the encodings list on the client side.

**Comment by bekriebel** [comment]
> this is expected and caused by Browser's internal logic on max layers to send for a particular resolution.
> 
> For `VideoPresets43.qhd`, even though we request the browser to send three encodings, but it decides to only send two. We try to deal with it to the best of our abilities on the server side, but do not end up updating the encodings list on the client side.

That makes sense. In that case, I think the change is good. Ultimately it looks like simulcast just isn't helpful in my situation.

**Review by bekriebel — APPROVED** [review]

**Comment by davidzhao** [comment]
If your video res is low-enough, it probably wouldn't matter.

**Comment by bekriebel** [comment]
> If your video res is low-enough, it probably wouldn't matter.

Yeah. I was noticing lower CPU and bandwidth usage with it enabled, but I just realized that that was because the logic was also changing the `videoEncoding` value based on my lower resolution and was dropping my main stream to 15fps. Once I forced that to be 30fps again, I started getting similar results with simulcast off and on, so I'm better off just leaving it off for my use case. I'm looking forward to testing with h264 encoding, though.

**Pull request merged**
