### PR TITLE
add api for updating room metadata

### PR DESCRIPTION
**Pull request by lukasIO**
I - very naively - copied the `updateParticipant` functions and adapted them for an `updateRoom` api.

Right now this is untested and I'm marking the PR as a draft. Just wanted to give space for feedback early in case I'm going about it entirely wrong.

### CODE REVIEW

**Comment by FeepsDev** [comment]
I think you should put the metadata variable as byte array so we can serialize whatever we want in it and define it in the protocol buffer messages.

You should also create a permission to allow users to edit the metadata.

I think you should also create a UpdateRoom we hook

**Comment by lukasIO** [comment]
Thanks for your feedback!

> metadata variable as byte array
I thought it might be useful to follow the same approach for the room metadata as for the participants. Me personally, as a user of livekit, would expect both kinds of metadata to behave similarily also in terms of payload. But I'm of course happy to change that if people see that differently.

> You should also create a permission to allow users to edit the metadata.
similar to before. updateParticipant is a server only api and I expected that the maintainers want to keep it that way for updateRoom

> You should also create a UpdateRoom webhook
nice idea! I will try to see if I can find out how to do that.

**Comment by davidzhao** [comment]
Hey @lukasIO, thanks for your contributions.

Do you have a particular use case in mind with this feature? That may give me a bit more context on how the feature should be structured.

We use protocol buffers to generate most of these definitions, so you'd first have to modify the members in the protocol repo, before the correct types will be generated: https://github.com/livekit/protocol. I'm happy to propose an API design with a bit more information about various use cases folks have. I'll post in issue too.

**Comment by lukasIO** [comment]
closing in favor of https://github.com/livekit/livekit-server/pull/126

**Pull request closed without merging**
