### PR TITLE
Include node ID with Prometheus metrics

### PR DESCRIPTION
**Pull request by matkam**

### CODE REVIEW

**Review by frostbyte73 — APPROVED** [review]
Lgtm

**Review by davidzhao — COMMENTED** [review]
lg, though tests are failing at startup

**Comment by matkam** [comment]
> lg, though tests are failing at startup

I'm reworking it now. I need to run `mage testall` before submitting these.

**Comment by matkam** [comment]
Reworked, keeping init static via https://github.com/livekit/protocol/pull/55

**Comment by matkam** [comment]
```
# HELP livekit_nack_total 
# TYPE livekit_nack_total counter
livekit_nack_total{direction="incoming",node_id="ND_kGcb4fFz"} 6
# HELP livekit_node_service_operation 
# TYPE livekit_node_service_operation counter
livekit_node_service_operation{error_type="",node_id="ND_kGcb4fFz",status="success",type="answer"} 1
livekit_node_service_operation{error_type="",node_id="ND_kGcb4fFz",status="success",type="ice_connection"} 1
livekit_node_service_operation{error_type="",node_id="ND_kGcb4fFz",status="success",type="offer"} 1
livekit_node_service_operation{error_type="",node_id="ND_kGcb4fFz",status="success",type="participant_join"} 1
livekit_node_service_operation{error_type="",node_id="ND_kGcb4fFz",status="success",type="signal_ws"} 1
# HELP livekit_packet_bytes 
# TYPE livekit_packet_bytes counter
livekit_packet_bytes{direction="incoming",node_id="ND_kGcb4fFz"} 231118
# HELP livekit_packet_total 
# TYPE livekit_packet_total counter
livekit_packet_total{direction="incoming",node_id="ND_kGcb4fFz"} 585
# HELP livekit_participant_total 
# TYPE livekit_participant_total gauge
livekit_participant_total{node_id="ND_kGcb4fFz"} 0
# HELP livekit_pli_total 
# TYPE livekit_pli_total counter
livekit_pli_total{direction="incoming",node_id="ND_kGcb4fFz"} 1
# HELP livekit_room_duration_seconds 
# TYPE livekit_room_duration_seconds histogram
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="5"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="10"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="60"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="300"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="600"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="1800"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="3600"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="7200"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="18000"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="36000"} 0
livekit_room_duration_seconds_bucket{node_id="ND_kGcb4fFz",le="+Inf"} 0
livekit_room_duration_seconds_sum{node_id="ND_kGcb4fFz"} 0
livekit_room_duration_seconds_count{node_id="ND_kGcb4fFz"} 0
# HELP livekit_room_total 
# TYPE livekit_room_total gauge
livekit_room_total 1
# HELP livekit_track_published_total 
# TYPE livekit_track_published_total gauge
livekit_track_published_total{kind="AUDIO",node_id="ND_kGcb4fFz"} 0
livekit_track_published_total{kind="VIDEO",node_id="ND_kGcb4fFz"} 0
```

**Pull request merged**
