### PR TITLE
Send stun servers to clients

### PR DESCRIPTION
**Pull request by davidzhao**
Flutter WebRTC stack requires the presence of STUN servers. For clients that are behind NATs, using STUN would also improve connectivity.

### CODE REVIEW

**Comment by hn8** [comment]
@davidzhao If turn.portUDP is not 0, maybe it should have preference over Google STUN (weird UDP port)? It also functions as STUN first and fallback to TURN. Is Flutter WebRTC ok with only "turn:" server.

**Comment by davidzhao** [comment]
That's a good point, if there's TURN/UDP, then we should definitely prefer that. I'll update.

**Comment by davidzhao** [comment]
If a user has specified their own STUN servers, we should respect that. However, if TURN/UDP is configured, then it should be using that as the default vs fallback (i.e. Google TURN)

**Review by hn8 — APPROVED** [review]
LGTM

**Pull request merged**
