### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by cnderrauber**
remove unused files, fields from ion-sfu.

### CODE REVIEW

**Review by frostbyte73 — APPROVED** [review]
Lgtm!

**Review by boks1971 — APPROVED** [review]
Awesome!

**Comment by frostbyte73** [comment]
If you run go mod tidy, I think there might be a couple extra dependencies like zerologr

**Comment by cnderrauber** [comment]
> If you run go mod tidy, I think there might be a couple extra dependencies like zerologr

Thanks, forget to run, done.

**Pull request merged**
